"""
Poker AI C++ Core Library Stub (Python 3.10 + CUDA 12.6)
=========================================================
本文件为 Pylance/VS Code 提供类型提示与中文文档，不参与运行时。
"""
from enum import Enum
from typing import List, Tuple, Callable, overload, Any

# ---------------------------------------------------------------------------
# Card
# ---------------------------------------------------------------------------
class Card:
    """一张扑克牌。"""
    suit: int
    """花色，0=红桃♥, 1=黑桃♠, 2=方块♦, 3=梅花♣"""
    rank: int
    """点数，0=2, 1=3, ..., 10=J, 11=Q, 12=K, 13=A"""

    def __init__(self, suit: int, rank: int) -> None: ...
    def index(self) -> int:
        """全局唯一索引 0~51（suit * 13 + rank）"""
        ...
    def to_string(self) -> str:
        """人类可读字符串，如 'Ah'、'2c'"""
        ...
    def to_protocol(self) -> str:
        """协议字符串 '<suit,rank>'，如 '<0,12>'"""
        ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# 模块级函数
# ---------------------------------------------------------------------------
def create_deck() -> List[Card]:
    """创建 52 张扑克牌"""
    ...

def parse_protocol_cards(s: str) -> List[Card]:
    """从协议字符串解析卡牌，如 'preflop|<0,12><1,11>'"""
    ...

# ---------------------------------------------------------------------------
# CardUtils
# ---------------------------------------------------------------------------
class CardUtils:
    """扑克牌工具类"""
    @staticmethod
    def create_deck() -> List[Card]: ...
    @staticmethod
    def parse_protocol_cards(msg: str) -> List[Card]: ...
    @staticmethod
    def cards_to_protocol(cards: List[Card]) -> str: ...

# ---------------------------------------------------------------------------
# 枚举
# ---------------------------------------------------------------------------
class Stage(Enum):
    """游戏阶段"""
    PREFLOP = ...
    FLOP = ...
    TURN = ...
    RIVER = ...
    SHOWDOWN = ...

class Position(Enum):
    """座位位置"""
    SB = ...
    BB = ...
    BUTTON = ...

class ActionType(Enum):
    """动作类型"""
    FOLD = ...
    CHECK = ...
    CALL = ...
    BET = ...
    RAISE = ...
    ALLIN = ...

# ---------------------------------------------------------------------------
# ActionRecord & GameState
# ---------------------------------------------------------------------------
class ActionRecord:
    """单条动作记录"""
    stage: Stage
    action: ActionType
    amount: int
    is_opponent: bool

class GameState:
    """当前游戏状态快照"""
    my_cards: List[Card]
    community_cards: List[Card]
    num_community: int
    my_position: Position
    stage: Stage
    my_chips: int
    opponent_chips: int
    pot: int
    to_call: int
    history: List[ActionRecord]
    opponent_vpip: float
    opponent_pfr: float
    opponent_af: float

    def __init__(self) -> None: ...
    def get_stage_history(self) -> List[ActionRecord]: ...
    def is_first_action(self) -> bool: ...

# ---------------------------------------------------------------------------
# HandEvaluator
# ---------------------------------------------------------------------------
class HandResult:
    """手牌评估结果"""
    rank: int
    kickers: Tuple[int, int, int, int, int]
    def __gt__(self, other: "HandResult") -> bool: ...
    def __eq__(self, other: object) -> bool: ...

class HandEvaluator:
    """7 张牌手牌评估器"""
    def __init__(self) -> None: ...
    def evaluate_7cards(self, cards: Tuple[Card, Card, Card, Card, Card, Card, Card]) -> HandResult: ...
    def evaluate_batch(self, hands: List[Tuple[Card, Card, Card, Card, Card, Card, Card]]) -> List[HandResult]: ...

# ---------------------------------------------------------------------------
# CFREngine
# ---------------------------------------------------------------------------
class CFREngine:
    """MCCFR 反事实遗憾最小化训练引擎"""
    def __init__(self) -> None: ...
    def make_info_set_key(self, state: GameState) -> str: ...
    def get_strategy(self, info_set_key: str) -> Tuple[float, float, float, float, float, float]: ...
    def get_average_strategy(self, info_set_key: str) -> Tuple[float, float, float, float, float, float]: ...
    def train_iteration(self, root_state: GameState) -> None: ...
    def train_iterations(self, n: int, root_state: GameState) -> None: ...
    def save_strategy(self, filepath: str) -> None: ...
    def load_strategy(self, filepath: str) -> None: ...
    def num_info_sets(self) -> int: ...

# ---------------------------------------------------------------------------
# WinRateCalculator
# ---------------------------------------------------------------------------
class WinRateCalculator:
    """蒙特卡洛胜率计算器"""
    def __init__(self) -> None: ...
    def calculate(self, my_cards: Tuple[Card, Card], community: List[Card], num_opponents: int, n_simulations: int) -> float: ...
    def calculate_batch(self, my_cards_list: List[Tuple[Card, Card]], community_list: List[List[Card]], num_opponents: int, n_simulations_each: int) -> List[float]: ...

# ---------------------------------------------------------------------------
# SelfPlayEnv
# ---------------------------------------------------------------------------
class StepResult:
    """step() 返回值"""
    state: GameState
    reward: float
    done: bool

class SelfPlayEnv:
    """自对弈环境"""
    def __init__(self) -> None: ...
    def reset(self, seed: int = 0) -> GameState: ...
    def step(self, action: ActionType, amount: int = 0) -> StepResult: ...
    def legal_actions(self) -> List[ActionType]: ...
    def is_action_legal(self, action: ActionType, amount: int = 0) -> bool: ...
    def step_batch(self, actions: List[ActionType], amounts: List[int]) -> List[StepResult]: ...
    def set_opponent_policy(self, policy: Callable[[GameState], ActionType]) -> None: ...
